name: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build: # 一项叫做build的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 13.14 # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "13.14"
    
    - name: Setup Hexo
      env:
        HEXO_DEPLOY_RSA: ${{ secrets.HEXO_DEPLOY_RSA }}
      run: |
        # 部署私钥文件
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_RSA" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # 设置git信息
        git config --global user.name '老刘头'
        git config --global user.email '1079655353@qq.com'
        # 安装依赖项目
        npm i -g hexo-cli
        npm i
  
    - name: Deploy
      run: |
        # publish
        hexo generate && hexo deploy # 执行部署程序
